#!/usr/bin/env python3
"""
Canonical entrypoint for running a query end-to-end.

Usage:
    python runtime/run_query.py --query "..." [--config <path>] [--json] [--provider <name>] [--model <name>]
"""
from pathlib import Path
import sys

# Ensure project root is on sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import bootstrap
import argparse
import json
import sys
import time
import uuid
from pathlib import Path
import logging

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from homllm.common.config import Config
from homllm.common.types import Intent
from homllm.context.pipeline import ContextPipeline
from homllm.generation.adapter import GenerationAdapter
from homllm.generation.interfaces import GenerationRequest, ModelConfig
from homllm.indexer.embedder import QwenEmbedder
from homllm.indexer.storage.filesystem_adapter import FilesystemAdapter
from homllm.ranking.pipeline import RankingPipeline
from homllm.retrieval.pipeline import RetrievalPipeline
from homllm.intelligence.controller import create_intelligence_controller
from homllm.context.applier import create_context_applier
from homllm.common.config import IntelligenceConfig
from runtime.logger import configure_logging


def format_duration_ms(start: float, end: float) -> float:
    """Convert duration to milliseconds."""
    return (end - start) * 1000


def print_answer_box(text: str) -> None:
    """
    Print answer text in a clean terminal box (no timestamps).
    
    Uses print() directly to bypass logger formatting.
    """
    box_width = 80
    border = "=" * box_width
    separator = "-" * box_width
    
    print()  # Blank line before box
    print(border)
    print("ANSWER")
    print(separator)
    
    if text and text.strip():
        # Print each line of the answer
        for line in text.splitlines():
            print(line)
    else:
        print("No output generated by model.")
    
    print(border)
    print()  # Blank line after box


logger = configure_logging(logger_name=__name__)


class PresentationRenderer:
    """
    Architecture-safe presentation renderer for user-facing output.
    
    Responsibilities:
    - Remove/abstract internal grounding markers (file hashes, symbol IDs)
    - Map file IDs to real file paths if shown
    - Map PARTIAL status to neutral user message
    - Preserve raw artifacts unchanged
    
    Constraints:
    - Pure, stateless, O(n) string processing
    - Configurable and bypassable for debug mode
    - No side effects on core logic
    """
    
    def __init__(
        self,
        artifacts_path: Path,
        normalize: bool = True,
        map_file_ids: bool = True,
    ):
        """
        Initialize presentation renderer.
        
        Args:
            artifacts_path: Path to indexes directory (for files.json)
            normalize: Enable normalization (disable for debug mode)
            map_file_ids: Map file hashes to real paths
        """
        self.artifacts_path = artifacts_path
        self.normalize = normalize
        self.map_file_ids = map_file_ids
        self._file_id_map: dict[str, str] | None = None
    
    def _load_file_metadata(self) -> dict[str, str]:
        """Lazy-load file_id -> path mapping."""
        if self._file_id_map is not None:
            return self._file_id_map
        
        self._file_id_map = {}
        try:
            fs_adapter = FilesystemAdapter(self.artifacts_path)
            if fs_adapter.exists("files.json"):
                files_data = fs_adapter.read_json("files.json")
                for file_info in files_data.get("files", []):
                    file_id = file_info.get("file_id")
                    file_path = file_info.get("path")
                    if file_id and file_path:
                        self._file_id_map[file_id] = file_path
        except Exception:
            # If metadata unavailable, continue without mapping
            pass
        
        return self._file_id_map
    
    def render(
        self,
        raw_text: str,
        status: str = "OK",
    ) -> str:
        """
        Render user-facing output from raw generation text.
        
        Args:
            raw_text: Raw generation output (preserved in artifacts)
            status: Generation status (OK, PARTIAL, ERROR)
        
        Returns:
            Normalized user-facing text with readable file references
        """
        if not self.normalize:
            return raw_text
        
        import re
        text = raw_text
        
        # Load file metadata for mapping hash IDs to file paths
        file_id_map = {}
        if self.map_file_ids:
            file_id_map = self._load_file_metadata()
        
        # Pattern 1: Map file hash IDs to readable file paths
        # Format: 16 hex chars followed by :line or :line-line
        # Example: "6157ae2fab7f3e72:1-133" -> "query_optimizer.py:1-133"
        def replace_file_hash(match: re.Match) -> str:
            file_id = match.group(1)
            line_ref = match.group(2)  # e.g., ":1-133" or ":45"
            
            if file_id_map and file_id in file_id_map:
                file_path = file_id_map[file_id]
                # Extract just the filename for readability
                file_name = Path(file_path).name
                return f"{file_name}{line_ref}"
            # If not found in map, keep original (better than empty)
            return match.group(0)
        
        text = re.sub(
            r'\b([a-f0-9]{16})(:\d+(?:-\d+)?)\b',
            replace_file_hash,
            text
        )
        
        # Pattern 2: Map symbol IDs to readable format
        # Format: file_id:symbol_name:line (file_id is 16 hex chars)
        # Example: "48dc8273aeda9734:_compute_file_hash:77" -> "file.py:_compute_file_hash:77"
        def replace_symbol_id(match: re.Match) -> str:
            full_match = match.group(0)
            parts = full_match.split(':')
            if len(parts) >= 3:
                file_id = parts[0]
                symbol_name = parts[1]
                line = parts[2]
                if file_id_map and file_id in file_id_map:
                    file_path = file_id_map[file_id]
                    file_name = Path(file_path).name
                    return f"{file_name}:{symbol_name}:{line}"
                # Keep original if not mappable
                return full_match
            return full_match
        
        text = re.sub(
            r'\b[a-f0-9]{16}:[a-zA-Z0-9_]+:\d+\b',
            replace_symbol_id,
            text
        )
        
        # Pattern 3: Map standalone file hash references to file names
        # Example: "(6157ae2fab7f3e72)" -> "(query_optimizer.py)"
        def replace_standalone_hash(match: re.Match) -> str:
            file_id = match.group(1)
            if file_id_map and file_id in file_id_map:
                file_path = file_id_map[file_id]
                file_name = Path(file_path).name
                return file_name
            return match.group(0)  # Keep original if not mappable
        
        text = re.sub(
            r'\b([a-f0-9]{16})\b(?!:[a-zA-Z0-9_]+:\d)',
            replace_standalone_hash,
            text
        )
        
        # Pattern 4: Remove standalone "NOT_IN_CONTEXT" markers
        text = re.sub(r'\bNOT_IN_CONTEXT\b', '[not in context]', text, flags=re.IGNORECASE)
        
        # Clean up extra whitespace
        text = re.sub(r' {2,}', ' ', text)
        text = re.sub(r'\n\s*\n\s*\n+', '\n\n', text)
        
        # Remove leading/trailing whitespace from lines
        lines = [line.strip() for line in text.split('\n')]
        text = '\n'.join(lines)
        
        return text.strip()
    
    def render_status_message(self, status: str) -> str | None:
        """
        Map internal status to neutral user-facing message.
        
        Args:
            status: Internal status (OK, PARTIAL, ERROR)
        
        Returns:
            User-facing message or None if no message needed
        """
        if not self.normalize:
            return None
        
        if status == "PARTIAL":
            return "Note: Some claims could not be fully verified from the provided context."
        
        return None


def print_telemetry(phase: str, **kwargs):
    """Print telemetry line in consistent format (duration-focused)."""
    parts = [f"[{phase}]"]
    for key, value in kwargs.items():
        if isinstance(value, float):
            parts.append(f"{key}={value:.2f}")
        else:
            parts.append(f"{key}={value}")
    logger.info(" ".join(parts))


def parse_intelligence_levels(spec: str) -> tuple[bool, bool, bool, bool]:
    """
    Parse intelligence level specification.
    
    Args:
        spec: Level spec string (none|l1|l1,l2|l1,l2,l3)
        
    Returns:
        Tuple of (enabled, l1_enabled, l2_enabled, l3_enabled)
        
    Raises:
        ValueError: If spec is invalid
    """
    spec = spec.lower().strip()
    if spec == "none":
        return (False, False, False, False)
    if spec == "l1":
        return (True, True, False, False)
    if spec == "l1,l2":
        return (True, True, True, False)
    if spec == "l1,l2,l3":
        return (True, True, True, True)
    raise ValueError(f"Invalid intelligence-levels: {spec}. Use: none|l1|l1,l2|l1,l2,l3")


def infer_retrieval_intent(query: str) -> Intent:
    """
    Infer retrieval intent from query text when CLI intent is not provided.

    Uses the existing deterministic sufficiency intent classifier and maps:
    - ARCHITECTURAL -> EXPLAIN
    - IMPLEMENTATION -> IMPLEMENT
    - BEHAVIORAL -> DEBUG
    """
    from homllm.sufficiency.intent import classify_intent

    result = classify_intent(query)
    mapping = {
        "ARCHITECTURAL": Intent.EXPLAIN,
        "IMPLEMENTATION": Intent.IMPLEMENT,
        "BEHAVIORAL": Intent.DEBUG,
    }
    return mapping.get(result.intent, Intent.UNKNOWN)


class QueryTelemetry:
    """Telemetry collector for query execution."""

    def __init__(self, query: str, export_json: bool = False):
        self.query = query
        self.should_export_json = export_json
        self.run_id = str(uuid.uuid4())
        self.phases = {}

    def record_phase(
        self,
        phase: str,
        start_time: float,
        end_time: float,
        **metadata,
    ):
        """Record phase telemetry."""
        duration_ms = format_duration_ms(start_time, end_time)

        phase_data = {
            "phase": phase,
            "duration_ms": duration_ms,
            **metadata,
        }

        self.phases[phase] = phase_data

        # Print telemetry
        print_telemetry(phase, duration_ms=f"{duration_ms:.0f}", **metadata)

    def write_json(self, output_path: Path):
        """Export telemetry as JSON."""
        telemetry_data = {
            "run_id": self.run_id,
            "query": self.query,
            "phases": self.phases,
        }

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(telemetry_data, f, indent=2, sort_keys=True)

        print_telemetry("TELEMETRY", json_export=str(output_path))


def _dump_candidate_diagnostics(
    run_id: str,
    retrieval_candidates,
    ranking_output,
    enabled: bool,
) -> None:
    """Write diagnostic-only candidate dumps for retrieval and ranking (no behavior changes)."""

    if not enabled:
        return

    trace_by_id: dict[str, object] = {}
    try:
        for t in getattr(ranking_output, "debug_traces", ()) or ():
            cid = getattr(t, "candidate_id", None)
            if cid:
                trace_by_id[str(cid)] = t
    except Exception:
        trace_by_id = {}

    retrieval_top20 = []
    for c in list(retrieval_candidates or [])[:20]:
        retrieval_top20.append(
            {
                "doc_id": getattr(c, "doc_id", None),
                "file": getattr(c, "file", None),
                "bm25_score": float(getattr(c, "bm25_score", 0.0) or 0.0),
                "vector_score": float(getattr(c, "vector_score", 0.0) or 0.0),
                "hybrid_score": float(getattr(c, "hybrid_score", 0.0) or 0.0),
            }
        )

    ranking_top20 = []
    ranked = list(getattr(ranking_output, "ranked_candidates", ()) or ())[:20]
    for c in ranked:
        doc_id = str(getattr(c, "doc_id", "") or "")
        t = trace_by_id.get(doc_id)
        ranking_top20.append(
            {
                "doc_id": getattr(c, "doc_id", None),
                "file": getattr(c, "file", None),
                "base_score": float(getattr(t, "base_score", 0.0) or 0.0),
                "rerank_score": float(getattr(t, "rerank_score", 0.0) or 0.0),
                "structural_score": float(getattr(t, "struct_bonus", 0.0) or 0.0),
                "final_score": float(getattr(t, "final_score", 0.0) or 0.0),
            }
        )

    payload = {
        "run_id": run_id,
        "retrieval_top20": retrieval_top20,
        "ranking_top20": ranking_top20,
    }

    out_path = Path("artifacts") / "runs" / run_id / "candidate_diagnostics.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def _run_and_save_diagnostic_layers(
    layers_arg: str,
    query: str,
    context_artifact,
    embedder,
    run_id: str,
) -> None:
    """
    Run selected P1–P4 diagnostic layers (read-only) and save their output to a separate file.
    layers_arg: comma-separated, e.g. 'p1,p2' or 'p1,p2,p3,p4'.
    """
    requested = [x.strip().lower() for x in layers_arg.split(",") if x.strip()]
    if not requested:
        return
    allowed = {"p1", "p2", "p3", "p4"}
    selected = [x for x in requested if x in allowed]
    if not selected:
        logger.warning("[DIAGNOSTIC_LAYERS] No valid layers in %r; allowed: p1,p2,p3,p4", layers_arg)
        return

    out = {}
    p1_result = None

    if "p1" in selected or "p2" in selected:
        from homllm.sufficiency import run_sufficiency
        p1_result = run_sufficiency(query, context_artifact, embedder)
        if "p1" in selected:
            out["p1"] = p1_result.to_dict()

    if "p2" in selected and p1_result is not None:
        from homllm.remediation import run_remediation_from_sufficiency
        p2_result = run_remediation_from_sufficiency(p1_result, fragility_flag=False)
        out["p2"] = p2_result.to_dict()

    if "p3" in selected:
        from homllm.instability import run_instability
        from homllm.instability.interfaces import RunRecord
        from homllm.sufficiency.intent import classify_intent

        intent = getattr(p1_result, "intent", "UNKNOWN") if p1_result else "UNKNOWN"
        verdict = getattr(p1_result, "final_verdict", "SUFFICIENT") if p1_result else "SUFFICIENT"

        def _embed_query_safe(text: str) -> tuple[float, ...] | None:
            try:
                v = embedder.embed_query(text) if embedder is not None else None
                if v is None:
                    return None
                values = tuple(float(x) for x in (v.values if hasattr(v, "values") else v))
                # Treat all-zero (or near-zero) vectors as "embedding unavailable" to avoid
                # pathological bucketing where even the current run is excluded.
                norm2 = sum(x * x for x in values)
                if norm2 <= 1e-12:
                    return None
                return values
            except Exception:
                return None

        # Build a lightweight history from prior artifact runs (best-effort).
        # This makes P3 informative (avoids permanent cold_start due to evidence_volume=1).
        history: list[RunRecord] = []
        artifacts_root = Path("artifacts") / "runs"
        try:
            run_dirs = sorted(
                [p for p in artifacts_root.iterdir() if p.is_dir()],
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
            for p in run_dirs[:200]:
                if p.name == run_id:
                    continue
                telemetry_path = p / "telemetry.json"
                if not telemetry_path.exists():
                    continue
                try:
                    telemetry = json.loads(telemetry_path.read_text(encoding="utf-8"))
                except Exception:
                    continue
                hist_query = telemetry.get("query", "")
                if not isinstance(hist_query, str) or not hist_query.strip():
                    continue

                hist_intent = classify_intent(hist_query).intent
                if hist_intent != intent:
                    continue

                chunk_ids: tuple[str, ...] = ()
                ctx_diag_path = p / "context_diagnostics.json"
                if ctx_diag_path.exists():
                    try:
                        ctx_diag = json.loads(ctx_diag_path.read_text(encoding="utf-8"))
                        l1_blocks = (ctx_diag.get("level1", {}) or {}).get("blocks", []) or []
                        chunk_ids = tuple(
                            b.get("block_id")
                            for b in l1_blocks
                            if isinstance(b, dict) and b.get("block_id")
                        )
                    except Exception:
                        chunk_ids = ()

                # Verdict is optional; default to SUFFICIENT if unknown.
                hist_verdict = "SUFFICIENT"
                diag_layers_path = p / "diagnostics.json"
                if diag_layers_path.exists():
                    try:
                        diag_layers = json.loads(diag_layers_path.read_text(encoding="utf-8"))
                        p1 = (diag_layers.get("layers", {}) or {}).get("p1", {}) or {}
                        hist_verdict = p1.get("final_verdict") or hist_verdict
                    except Exception:
                        pass

                history.append(
                    RunRecord(
                        query=hist_query,
                        intent=hist_intent,
                        chunk_ids=chunk_ids,
                        file_paths=(),
                        answer_text="",
                        final_verdict=hist_verdict,
                        policy_influenced=False,
                        query_embedding=_embed_query_safe(hist_query),
                    )
                )
                if len(history) >= 40:
                    break
        except Exception:
            history = []

        # Include current run as the final record.
        history.append(
            RunRecord(
                query=query,
                intent=intent,
                chunk_ids=tuple(b.block_id for b in context_artifact.blocks),
                file_paths=tuple(b.file for b in context_artifact.blocks),
                answer_text="",
                final_verdict=verdict,
                policy_influenced=False,
                query_embedding=_embed_query_safe(query),
            )
        )

        p3_result = run_instability(tuple(history), intent, reference_embedding=_embed_query_safe(query))
        out["p3"] = p3_result.to_dict()

    if "p4" in selected:
        from homllm.explanation_gap import run_explanation_gap
        p4_result = run_explanation_gap(query, history_stats=None)
        out["p4"] = p4_result.to_dict()

    # Build final output with run metadata (matching telemetry.json structure)
    final_output = {
        "run_id": run_id,
        "query": query,
        "layers": out,
    }

    output_path = Path("artifacts") / "runs" / run_id / "diagnostics.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(final_output, f, indent=2, ensure_ascii=False)
    print_telemetry("DIAGNOSTIC_LAYERS", saved=str(output_path), layers=",".join(selected))


def _run_and_save_context_diagnostics(
    context_artifact,
    run_id: str,
) -> None:
    """
    Run L1/L2/L3 context diagnostics (read-only) and save output to context_diagnostics.json.
    
    Uses diagnostics_runner.run_diagnostics() which analyzes:
    - L1: Per-block diagnostics (token counts, quality signals)
    - L2: Relational diagnostics (block similarity, redundancy, gaps)
    - L3: Summary diagnostics (intent, roles, load, failure modes)
    """
    from dataclasses import asdict, is_dataclass
    from homllm.intelligence.diagnostics_runner import run_diagnostics
    
    def safe_serialize(obj):
        """Recursively convert dataclasses and handle non-JSON types."""
        if obj is None:
            return None
        if is_dataclass(obj) and not isinstance(obj, type):
            return {k: safe_serialize(v) for k, v in asdict(obj).items()}
        if isinstance(obj, (list, tuple)):
            return [safe_serialize(item) for item in obj]
        if isinstance(obj, dict):
            return {k: safe_serialize(v) for k, v in obj.items()}
        if isinstance(obj, (str, int, float, bool)):
            return obj
        # Fallback: convert to string
        return str(obj)
    
    try:
        snapshot = run_diagnostics(context_artifact, force_run=True)
        if snapshot is None:
            logger.warning("[CONTEXT_DIAGNOSTICS] Diagnostics returned None")
            return
        
        # Build output structure with safe serialization
        output = {
            "run_id": run_id,
            "level1": {
                "status": snapshot.level1.status,
                "reason": snapshot.level1.reason,
                "blocks": [
                    {
                        "block_id": b.block_id,
                        "tokens": b.tokens,
                        "noise_ratio": getattr(b, "noise_ratio", None),
                        "structural_dominance": getattr(b, "structural_dominance", None),
                    }
                    for b in snapshot.level1.blocks
                ] if snapshot.level1.blocks else [],
                "result": safe_serialize(snapshot.level1.result) if snapshot.level1.result else None,
            },
            "level2": {
                "status": snapshot.level2.status,
                "reason": snapshot.level2.reason,
                "result": safe_serialize(snapshot.level2.result) if snapshot.level2.result else None,
            },
            "level3": {
                "status": snapshot.level3.status,
                "reason": snapshot.level3.reason,
                "result": safe_serialize(snapshot.level3.result) if snapshot.level3.result else None,
            },
        }
        
        output_path = Path("artifacts") / "runs" / run_id / "context_diagnostics.json"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(output, f, indent=2, ensure_ascii=False)
        
        print_telemetry(
            "CONTEXT_DIAGNOSTICS",
            saved=str(output_path),
            l1_status=snapshot.level1.status,
            l2_status=snapshot.level2.status,
            l3_status=snapshot.level3.status,
        )
    except Exception as e:
        logger.warning("[CONTEXT_DIAGNOSTICS] Failed: %s", e, exc_info=True)


def main():
    """Main entrypoint."""
    parser = argparse.ArgumentParser(description="Run a query end-to-end")
    parser.add_argument("--query", type=str, required=True, help="Query string")
    parser.add_argument("--config", type=Path, default=Path("configs/default.yaml"), help="Config file path")
    parser.add_argument("--json", action="store_true", help="Export JSON telemetry")
    parser.add_argument("--provider", type=str, help="Generation provider (gemini, openai, local)")
    parser.add_argument("--model", type=str, help="Generation model name")
    parser.add_argument("--intent", type=str, default="UNKNOWN", help="Query intent")
    parser.add_argument("--raw", action="store_true", help="Disable presentation normalization (debug mode)")
    parser.add_argument("--no-file-mapping", action="store_true", help="Disable file ID to path mapping")
    parser.add_argument("--token-attribution", action="store_true", 
                        help="Emit token attribution telemetry")
    parser.add_argument("--intelligence-levels", type=str, default=None,
                        help="Override intelligence levels: none|l1|l1,l2|l1,l2,l3")
    parser.add_argument("--assertion-audit", action="store_true",
                        help="Emit assertion suppression audit telemetry")
    parser.add_argument("--assertion-readability", action="store_true",
                        help="Emit assertion readability telemetry")
    parser.add_argument("--reasoning-diagnostics", action="store_true",
                        help="Emit reasoning diagnostic telemetry")
    parser.add_argument("--reasoning-contracts", action="store_true",
                        help="Emit reasoning contract telemetry")
    parser.add_argument("--diagnostic-layers", type=str, default=None,
                        help="Comma-separated: p1,p2,p3,p4. Run P1–P4 diagnostic layers and save to a separate file (e.g. p1,p2 or p1,p2,p3,p4).")
    parser.add_argument("--context-diagnostics", action="store_true",
                        help="Run L1/L2/L3 context diagnostics (per-block, relational, summary) and save to context_diagnostics.json")
    parser.add_argument(
        "--diagnostics-only",
        action="store_true",
        help="Stop after retrieval/ranking/context (+ optional diagnostics). Skips Plan C and generation.",
    )

    args = parser.parse_args()

    # Load config
    if not args.config.exists():
        logger.error(f"Error: Config file does not exist: {args.config}")
        sys.exit(1)

    try:
        config = Config.from_file(args.config)
        indexer_config = config.get_indexer_config()
        retrieval_config = config.get_retrieval_config()
        ranking_config = config.get_ranking_config()
        context_config = config.get_context_config()
        intelligence_config = config.get_intelligence_config()
        generation_config = config.get_generation_config()
    except Exception as e:
        logger.error(f"Error loading config: {e}")
        sys.exit(1)

    # Override intelligence config if CLI flag provided
    if args.intelligence_levels:
        try:
            enabled, l1, l2, l3 = parse_intelligence_levels(args.intelligence_levels)
            intelligence_config = IntelligenceConfig(
                enabled=enabled,
                level1_enabled=l1,
                level2_enabled=l2,
                level3_enabled=l3,
            )
            logger.info(f"[INTELLIGENCE_OVERRIDE] levels={args.intelligence_levels}")
        except ValueError as e:
            logger.error(f"Error: {e}")
            sys.exit(1)

    # Initialize telemetry
    telemetry = QueryTelemetry(args.query, export_json=args.json)

    # Parse intent
    intent_source = "cli"
    try:
        intent = Intent[args.intent.upper()]
    except KeyError:
        intent = Intent.UNKNOWN
        intent_source = "inferred"

    if intent == Intent.UNKNOWN:
        intent = infer_retrieval_intent(args.query)
        intent_source = "inferred"

    logger.info("[INTENT] value=%s source=%s", intent.value, intent_source)
    diagnostics_enabled = bool(args.diagnostic_layers) or bool(args.context_diagnostics)

    try:
        # Initialize presentation renderer (architecture-safe, deterministic)
        presentation_renderer = PresentationRenderer(
            artifacts_path=indexer_config.storage.artifacts_path,
            normalize=not args.raw,
            map_file_ids=not args.no_file_mapping,
        )

        # Initialize embedder (shared across retrieval and context)
        embedder = QwenEmbedder(
            model_name=indexer_config.embedding_model,
            dimension=indexer_config.embedding_dimension,
            max_input_tokens=indexer_config.embedding_max_tokens,
        )

        # Phase 1: Retrieval
        retrieval_start = time.perf_counter()
        retrieval_pipeline = RetrievalPipeline(
            config=retrieval_config,
            bm25_index_path=indexer_config.storage.tantivy_path,
            vector_db_path=indexer_config.storage.lancedb_path,
            duckdb_path=indexer_config.storage.duckdb_path,
            artifacts_path=indexer_config.storage.artifacts_path,
            embedder=embedder,
        )

        retrieval_result = retrieval_pipeline.retrieve(args.query, intent=intent)
        retrieval_end = time.perf_counter()

        telemetry.record_phase(
            "RETRIEVAL",
            retrieval_start,
            retrieval_end,
            candidates=len(retrieval_result.candidates),
            bm25_count=retrieval_result.metadata.get("bm25_count", 0),
            vector_count=retrieval_result.metadata.get("vector_count", 0),
            merged_count=retrieval_result.metadata.get("merged_count", 0),
            prep_ms=retrieval_result.metadata.get("prep_ms"),
            bm25_ms=retrieval_result.metadata.get("bm25_ms"),
            vector_ms=retrieval_result.metadata.get("vector_ms"),
            merge_ms=retrieval_result.metadata.get("merge_ms"),
            mmr_ms_merger=retrieval_result.metadata.get("mmr_ms_merger"),
            granularity_ms=retrieval_result.metadata.get("granularity_ms"),
            graph_stitch_ms=retrieval_result.metadata.get("graph_stitch_ms"),
            expansion_ms=retrieval_result.metadata.get("expansion_ms"),
            precision_ms=retrieval_result.metadata.get("precision_ms"),
            precision_recovery_added=retrieval_result.metadata.get("precision_recovery_added"),
            precision_recovery_cap=retrieval_result.metadata.get("precision_recovery_cap"),
            precision_recovery_conf_mean=retrieval_result.metadata.get("precision_recovery_conf_mean"),
            total_ms=retrieval_result.metadata.get("total_ms"),
            plan_b_active=retrieval_result.metadata.get("plan_b_active"),
            is_legacy_index=retrieval_result.metadata.get("is_legacy_index"),
            search_mode=retrieval_result.metadata.get("search_mode"),
            vector_calibration_mode=retrieval_result.metadata.get("vector_calibration_mode"),
            static_ceiling_mode=retrieval_result.metadata.get("static_ceiling_mode"),
            effective_bm25_top_k=retrieval_result.metadata.get("effective_bm25_top_k"),
            effective_vector_top_k=retrieval_result.metadata.get("effective_vector_top_k"),
            effective_post_merge_candidates=retrieval_result.metadata.get("effective_post_merge_candidates"),
            effective_output_top_k=retrieval_result.metadata.get("effective_output_top_k"),
            query_expansion_enabled=retrieval_result.metadata.get("query_expansion_enabled"),
            query_expansion_term_count=retrieval_result.metadata.get("query_expansion_term_count"),
            query_expansion_terms=",".join(retrieval_result.metadata.get("query_expansion_terms", [])),
        )

        if not retrieval_result.candidates:
            logger.warning("No candidates retrieved")
            return

        # Phase 2: Ranking
        ranking_start = time.perf_counter()

        # Load callgraph for ranking
        callgraph = {}
        fs_adapter = FilesystemAdapter(indexer_config.storage.artifacts_path)
        if fs_adapter.exists("callgraph.json"):
            callgraph_data = fs_adapter.read_json("callgraph.json")
            for edge in callgraph_data.get("edges", []):
                caller_id = edge.get("caller_id")
                callee_id = edge.get("callee_id")
                if caller_id and callee_id:
                    if caller_id not in callgraph:
                        callgraph[caller_id] = []
                    callgraph[caller_id].append(callee_id)

        ranking_pipeline = RankingPipeline(
            config=ranking_config,
            callgraph=callgraph,
        )

        from homllm.ranking.interfaces import RankingInput

        ranking_input = RankingInput(
            query=args.query,
            candidates=tuple(retrieval_result.candidates),
            config=ranking_config,
        )

        ranking_output = ranking_pipeline.rank(ranking_input)
        ranking_end = time.perf_counter()

        telemetry.record_phase(
            "RANKING",
            ranking_start,
            ranking_end,
            candidates=len(ranking_output.ranked_candidates),
            reranker=ranking_output.metadata.reranker_used,
            reranker_unavailable=ranking_output.metadata.reranker_unavailable,
            set_optimization=ranking_output.metadata.set_optimization,
            signal_profile=ranking_output.metadata.signal_profile,
            ranking_concentration=ranking_output.metadata.ranking_concentration,
            ranking_geometry=ranking_output.metadata.ranking_geometry,
        )

        # Diagnostic-only candidate dump (no behavior changes).
        _dump_candidate_diagnostics(
            run_id=telemetry.run_id,
            retrieval_candidates=retrieval_result.candidates,
            ranking_output=ranking_output,
            enabled=bool(args.diagnostic_layers) or bool(args.context_diagnostics),
        )

        # Phase 3: Context Assembly
        context_start = time.perf_counter()
        context_pipeline = ContextPipeline(
            config=context_config,
            embedder=embedder,
        )

        context_artifact = context_pipeline.assemble(
            ranking_output=ranking_output,
            query=args.query,
            query_id=retrieval_result.query_id,
        )
        context_end = time.perf_counter()

        telemetry.record_phase(
            "CONTEXT",
            context_start,
            context_end,
            blocks=len(context_artifact.blocks),
            tokens=context_artifact.used_tokens,
            token_budget=context_artifact.token_budget,
            generation_reserve=context_config.generation_reserve_tokens,
            tokens_remaining=context_config.max_tokens - context_artifact.used_tokens,
            ranking_surface_lock_enabled=context_artifact.provenance.get(
                "ranking_surface_lock_enabled"
            ),
            ranking_order_preserved=context_artifact.provenance.get(
                "ranking_order_preserved"
            ),
            context_reorder_count=context_artifact.provenance.get(
                "context_reorder_count"
            ),
            stage_counts=context_artifact.provenance.get("stage_counts"),
            drop_trace=(
                context_artifact.provenance.get("context_drop_trace")
                if diagnostics_enabled
                else None
            ),
            context_synthesis=context_artifact.provenance.get("context_synthesis"),
            context_integration=context_artifact.provenance.get("context_integration"),
            stage_file_histograms=(
                context_artifact.provenance.get("stage_file_histograms")
                if diagnostics_enabled
                else None
            ),
            scored_order_top10=(
                context_artifact.provenance.get("scored_order_top10")
                if diagnostics_enabled
                else None
            ),
        )

        # Phase 4: Intelligence Analysis + Context Application
        # Record tokens before for telemetry
        tokens_before = context_artifact.used_tokens
        
        if intelligence_config.enabled:
            intelligence_start = time.perf_counter()
            
            # Create intelligence controller with config
            intelligence_controller = create_intelligence_controller(
                level1_enabled=intelligence_config.level1_enabled,
                level2_enabled=intelligence_config.level2_enabled,
                level3_enabled=intelligence_config.level3_enabled,
                audit_enabled=getattr(args, 'assertion_audit', False),
                assertion_readability_enabled=getattr(args, 'assertion_readability', False),
            )

            # Run intelligence analysis (diagnostics run once)
            modification_plan = intelligence_controller.run(context_artifact)
            
            # Apply modification plan to context
            applier = create_context_applier()
            applier_result = applier.apply(modification_plan, context_artifact)
            
            # Use the new context from applier
            context_artifact = applier_result.context
            diff = applier_result.diff
            
            intelligence_end = time.perf_counter()

            telemetry.record_phase(
                "INTELLIGENCE",
                intelligence_start,
                intelligence_end,
                intelligence_enabled=True,
                levels_executed=len(modification_plan.levels_executed),
                total_actions=modification_plan.total_actions,
                actions_applied=diff.total_changes,
                diff_entries=len(diff.entries),
                context_tokens_before=tokens_before,
                context_tokens_after=context_artifact.used_tokens,
            )
            
            # Emit assertion audit telemetry if enabled
            if getattr(args, 'assertion_audit', False) and modification_plan.audit_result:
                audit = modification_plan.audit_result
                print_telemetry(
                    "ASSERTION_AUDIT",
                    total_assertions=audit.total_assertions_considered,
                    suppressed=audit.assertions_suppressed,
                    unblocked=audit.assertions_unblocked,
                )
                # Optionally print detailed suppression breakdown
                if audit.suppression_breakdown_by_level:
                    breakdown = {f"L{lvl}": cnt for lvl, cnt in audit.suppression_breakdown_by_level}
                    print_telemetry("ASSERTION_AUDIT_BREAKDOWN", **breakdown)
            
            # Emit assertion readability telemetry if enabled
            if getattr(args, 'assertion_readability', False) and modification_plan.readability_result:
                readability = modification_plan.readability_result
                print_telemetry(
                    "ASSERTION_READABILITY",
                    total_blocks=readability.total_blocks,
                    readable=readability.readable_count,
                    suppressed=readability.suppressed_count,
                    protected_but_readable=readability.protected_but_readable_count,
                )
        else:
            # Intelligence disabled - skip entirely
            telemetry.record_phase(
                "INTELLIGENCE",
                time.perf_counter(),
                time.perf_counter(),
                intelligence_enabled=False,
                levels_executed=0,
                total_actions=0,
                actions_applied=0,
                diff_entries=0,
                context_tokens_before=tokens_before,
                context_tokens_after=tokens_before,
            )

        # Optional: P1–P4 diagnostic layers (read-only; save to separate file for diagnostic visibility)
        if getattr(args, "diagnostic_layers", None):
            _run_and_save_diagnostic_layers(
                args.diagnostic_layers,
                args.query,
                context_artifact,
                embedder,
                telemetry.run_id,
            )

        # Optional: L1/L2/L3 context diagnostics (read-only; save to separate file)
        if getattr(args, "context_diagnostics", False):
            _run_and_save_context_diagnostics(
                context_artifact,
                telemetry.run_id,
            )

        # Diagnostics-only mode: export telemetry and exit without generation.
        if getattr(args, "diagnostics_only", False):
            gen_start = time.perf_counter()
            gen_end = time.perf_counter()
            telemetry.record_phase(
                "GENERATION",
                gen_start,
                gen_end,
                provider="none",
                model="none",
                tokens_in=0,
                tokens_out=0,
                status="SKIPPED",
                finish_reason="diagnostics_only",
            )

            if args.json:
                artifacts_path = Path("artifacts") / "runs" / telemetry.run_id
                telemetry.write_json(artifacts_path / "telemetry.json")

            print_answer_box("[diagnostics-only] Skipped generation.")
            return

        # =====================================================================
        # Plan C: Mechanical Fixer + ABRM Activation
        # =====================================================================
        # 
        # Authority ordering: P1-P4 diagnostics → Mechanical Fixer → ABRM → Generation
        # Invariants:
        # - Max one action per query
        # - Deterministic (same diagnostics → same action)
        # - No LLM calls, no retries
        # - Config-gated: mechanical_fixer_enabled, abrm_enabled
        #
        fixer_result = None
        abrm_active = False
        mechanical_fix_notice = ""
        p1_result = None
        p2_result = None
        p2_budget_delta = 0
        
        # Check if mechanical fixer is enabled in config
        intelligence_cfg = getattr(config, "intelligence", {}) or {}
        mechanical_fixer_enabled = intelligence_cfg.get("mechanical_fixer_enabled", False)
        abrm_enabled = intelligence_cfg.get("abrm_enabled", False)
        p2_budget_increase_pct = float(intelligence_cfg.get("p2_budget_increase_pct", 40))

        # -----------------------------------------------------------------
        # P2 Remediation: TOKEN_BUDGET_INCREASE (execute, then reassemble)
        # -----------------------------------------------------------------
        try:
            from dataclasses import replace
            from homllm.sufficiency import run_sufficiency
            from homllm.remediation import run_remediation_from_sufficiency

            p1_result = run_sufficiency(args.query, context_artifact, embedder)
            p2_result = run_remediation_from_sufficiency(p1_result, fragility_flag=False)

            has_budget_action = any(
                action.action_type == "TOKEN_BUDGET_INCREASE"
                for action in p2_result.actions
            )
            if has_budget_action:
                current_budget = context_artifact.token_budget
                increased_budget = int(current_budget * (1.0 + (p2_budget_increase_pct / 100.0)))
                capped_budget = min(increased_budget, context_config.max_tokens)

                if capped_budget > current_budget:
                    # Reduce generation reserve to allow more context tokens
                    new_reserve = max(0, context_config.max_tokens - capped_budget)
                    boosted_context_config = replace(
                        context_config,
                        generation_reserve_tokens=new_reserve,
                    )
                    boosted_pipeline = ContextPipeline(
                        config=boosted_context_config,
                        embedder=embedder,
                    )
                    context_artifact = boosted_pipeline.assemble(
                        ranking_output=ranking_output,
                        query=args.query,
                        query_id=retrieval_result.query_id,
                    )
                    p2_budget_delta = capped_budget - current_budget
                    context_artifact = replace(
                        context_artifact,
                        explain_trace=context_artifact.explain_trace + (
                            f"p2_budget_increased:+{p2_budget_delta} tokens",
                        ),
                    )
                    print_telemetry(
                        "P2_REMEDIATION",
                        p2_budget_increased=p2_budget_delta,
                        previous_tokens=current_budget,
                        target_tokens=capped_budget,
                    )
        except Exception as e:
            logger.warning(f"Plan C: P2 budget remediation failed: {e}")
        
        if mechanical_fixer_enabled:
            fixer_start = time.perf_counter()
            
            try:
                from homllm.intelligence.mechanical_fixer import (
                    MechanicalFixer,
                    should_activate_abrm,
                    ABRMConfig,
                )
                from homllm.intelligence.fixer_config import get_fixer_config, get_abrm_config
                from homllm.intelligence.diagnostics_runner import run_diagnostics
                
                # Get configs
                fixer_config = get_fixer_config(config)
                abrm_config = get_abrm_config(config)
                
                # Run diagnostics (reuse cached if already run)
                diagnostics = run_diagnostics(context_artifact, force_run=False)
                
                if diagnostics:
                    # Apply mechanical fixer (max 1 action)
                    fixer = MechanicalFixer(
                        fixer_config,
                        duckdb_path=indexer_config.storage.duckdb_path,
                    )
                    context_artifact, fixer_result = fixer.apply(context_artifact, diagnostics)
                    
                    # Determine ABRM activation
                    if abrm_enabled:
                        abrm_active = should_activate_abrm(
                            diagnostics, fixer_result, abrm_config, context_artifact
                        )
                        if p1_result is not None:
                            if p1_result.final_verdict in ("PROBABLY_SUFFICIENT", "INSUFFICIENT"):
                                abrm_active = True
                        if p2_result is not None and p2_result.actions:
                            abrm_active = True
                    
                    # Format priming notice for injection
                    if fixer_result and fixer_result.was_applied:
                        mechanical_fix_notice = fixer_result.format_priming_notice()
                    
                    fixer_end = time.perf_counter()
                    
                    # Telemetry: Mechanical Fixer
                    if fixer_result:
                        print_telemetry(
                            "MECHANICAL_FIXER",
                            action=fixer_result.action.value,
                            trigger=fixer_result.trigger,
                            blocks_added=fixer_result.delta.get("blocks_added", 0),
                            blocks_removed=fixer_result.delta.get("blocks_removed", 0),
                            improved=fixer_result.improved,
                            duration_ms=format_duration_ms(fixer_start, fixer_end),
                        )
                    
                    # Telemetry: ABRM
                    if abrm_active:
                        print_telemetry(
                            "ABRM",
                            active=True,
                            trigger="diagnostics_or_fixer_or_p1p2",
                        )
                else:
                    logger.debug("Plan C: Diagnostics not available, skipping mechanical fixer")
                    
            except Exception as e:
                logger.warning(f"Plan C: Mechanical fixer failed: {e}")
                # Continue with original context (fixer is optional)

        # Force ABRM activation based on P1/P2 even if fixer is disabled
        if abrm_enabled and not abrm_active:
            if p1_result is not None and p1_result.final_verdict in ("PROBABLY_SUFFICIENT", "INSUFFICIENT"):
                abrm_active = True
            if p2_result is not None and p2_result.actions:
                abrm_active = True
            if abrm_active:
                print_telemetry(
                    "ABRM",
                    active=True,
                    trigger="p1_or_p2",
                )

        # Phase 4b: Build reasoning contracts (pre-generation)
        # Contracts define what MUST be reasoned before generation
        reasoning_contract = None
        if getattr(args, 'reasoning_contracts', False):
            from homllm.intelligence.reasoning_contracts import create_contract_collector
            from homllm.intelligence.reasoning_diagnostic import (
                ReasoningDiagnosticResult,
                ReasoningExpectation,
                ReasoningFailure,
                EvidenceSummary,
                DiagnosticConfidence,
                QueryTypeFlag,
            )
            from homllm.intelligence.assertion_readability import ReadabilityResult
            
            # Get readability result from plan
            readability_result = (
                modification_plan.readability_result 
                if 'modification_plan' in dir() and modification_plan.readability_result 
                else ReadabilityResult.empty()
            )
            
            # Build expectations from query (same logic as RDL evaluator)
            from homllm.intelligence.reasoning_diagnostic.evaluator import ReasoningDiagnosticEvaluator
            evaluator = ReasoningDiagnosticEvaluator()
            query_flags = evaluator._detect_query_type(args.query.lower())
            
            # Count distinct components
            distinct_components = len(set(b.file for b in context_artifact.blocks)) if context_artifact.blocks else 0
            
            # Create minimal diagnostic result for contract building
            pre_gen_diagnostic = ReasoningDiagnosticResult(
                query_type_flags=tuple(query_flags),
                expectations=ReasoningExpectation(
                    aggregation_expected=QueryTypeFlag.ENUMERATIVE in query_flags,
                    interaction_expected=QueryTypeFlag.INTERACTIONAL in query_flags,
                    trace_expected=QueryTypeFlag.TRACE in query_flags,
                ),
                failures=ReasoningFailure(False, False, False),  # Pre-gen, no failures yet
                evidence=EvidenceSummary(
                    readable_blocks=readability_result.readable_count,
                    distinct_components_detected=distinct_components,
                    enumeration_markers_found=False,
                    interaction_markers_found=False,
                    surrender_phrases_found=False,
                ),
                confidence=DiagnosticConfidence.MODERATE,
            )
            
            contract_collector = create_contract_collector(enabled=True)
            reasoning_contract = contract_collector.collect(
                diagnostic_result=pre_gen_diagnostic,
                readability_result=readability_result,
                context=context_artifact,
            )
            
            if reasoning_contract.has_requirements:
                print_telemetry(
                    "REASONING_CONTRACTS",
                    required_steps=",".join(reasoning_contract.step_names),
                    severity=reasoning_contract.severity.value,
                    constraint_count=len(reasoning_contract.constraints),
                )

        # Phase 5: Generation
        generation_start = time.perf_counter()

        # Select provider
        provider_name = args.provider or generation_config.default_provider
        if provider_name == "gemini":
            from homllm.generation.providers import GeminiProvider

            provider = GeminiProvider()
        elif provider_name == "openai":
            from homllm.generation.providers import OpenAIProvider

            provider = OpenAIProvider()
        elif provider_name == "local":
            from homllm.generation.providers import LocalProvider

            provider = LocalProvider()
        else:
            logger.error(f"Error: Unknown provider: {provider_name}")
            sys.exit(1)

        model_name = args.model or generation_config.default_model
        generation_adapter = GenerationAdapter(
            provider=provider,
            default_model=model_name,
        )

        model_config = ModelConfig(
            temperature=generation_config.default_temperature,
            max_output_tokens=generation_config.default_max_output_tokens,
        )

        # =====================================================================
        # Phase-3A/3B/3C: Reasoning Contract Enforcement + Prompt Integrity
        # =====================================================================
        # 
        # Phase-3A: Render reasoning obligations
        # Phase-3B: Render structure requirements
        # Phase-3C: Completion guard + prompt integrity
        #
        # GUARANTEE: All template variables are assembled BEFORE rendering
        # GUARANTEE: Each variable is injected EXACTLY ONCE
        # GUARANTEE: Empty string when disabled (zero side effects)
        
        enforcement_prompt = ""
        structure_prompt = ""
        completion_guard_prompt = ""
        
        if reasoning_contract and reasoning_contract.has_requirements:
            from homllm.intelligence.reasoning_contracts import (
                create_contract_enforcer,
                create_structure_enforcer,
                create_completion_guard,
            )
            # Phase-3A: Reasoning obligations
            enforcer = create_contract_enforcer()
            enforcement_prompt = enforcer.render(reasoning_contract)
            logger.debug(f"Phase-3A: Enforcement prompt injected: {len(enforcement_prompt)} chars")
            
            # Phase-3B: Answer structure requirements
            structure_enforcer = create_structure_enforcer()
            structure_prompt = structure_enforcer.render(reasoning_contract)
            logger.debug(f"Phase-3B: Structure prompt injected: {len(structure_prompt)} chars")
            
            # Phase-3C: Completion guard (stop instructions)
            completion_guard = create_completion_guard()
            completion_guard_prompt = completion_guard.render(reasoning_contract)
            logger.debug(f"Phase-3C: Completion guard injected: {len(completion_guard_prompt)} chars")
        
        # Phase-3C: Assemble template variables with guaranteed integrity
        # All required variables MUST exist before this point
        from homllm.intelligence.reasoning_contracts import create_prompt_integrity_guard
        
        prompt_guard = create_prompt_integrity_guard()
        template_variables = {
            "reasoning_enforcement": enforcement_prompt,
            "structure_requirements": structure_prompt,
            "completion_guard": completion_guard_prompt,
        }
        
        # Fill any missing required variables with empty string
        template_variables = prompt_guard.validate_and_fill(template_variables)
        
        # Phase-3C: Hard assertion - catch injection bugs early
        # This will raise AssertionError if any required variable is missing
        prompt_guard.assert_integrity(template_variables)
        
        # =====================================================================
        # Plan C: ABRM Template Selection
        # =====================================================================
        # Select template: ABRM if activated, else base "explain"
        # ABRM template includes explicit Assumptions section
        #
        from homllm.generation.template_loader import TemplateLoader
        
        template_loader = TemplateLoader()
        selected_template = template_loader.select_template("explain", abrm_active=abrm_active)
        
        # Inject Plan C template variables
        template_variables["mechanical_fix_notice"] = mechanical_fix_notice
        template_variables["query"] = args.query
        template_variables["context"] = context_artifact.context_text
        
        # Build provenance summary for ABRM template
        provenance_parts = []
        if context_artifact.blocks:
            unique_files = len(set(b.file for b in context_artifact.blocks))
            provenance_parts.append(f"{len(context_artifact.blocks)} blocks from {unique_files} files")
        if fixer_result and fixer_result.was_applied:
            provenance_parts.append(f"Fix: {fixer_result.action.value}")
        template_variables["provenance_summary"] = "; ".join(provenance_parts) if provenance_parts else "Standard retrieval"
        template_variables["fix_summary"] = mechanical_fix_notice or "None"

        logger.debug(f"Plan C: template={selected_template}, abrm_active={abrm_active}")

        # Telemetry: rendered prompt excerpt for debug
        try:
            rendered_prompt = template_loader.render(selected_template, template_variables)
            prompt_excerpt = rendered_prompt[:200].replace("\n", " ")
            print_telemetry("PROMPT_RENDER", template=selected_template, excerpt=prompt_excerpt)
        except Exception as e:
            logger.warning(f"Prompt render preview failed: {e}")
        
        generation_request = GenerationRequest(
            request_id=retrieval_result.query_id,
            query=args.query,
            intent=intent,
            context_artifact=context_artifact,
            prompt_template=selected_template,
            template_variables=template_variables,
            output_mode="TEXT",
            model_config=model_config,
        )

        generation_result = generation_adapter.generate(generation_request)
        generation_end = time.perf_counter()

        telemetry.record_phase(
            "GENERATION",
            generation_start,
            generation_end,
            provider=provider_name,
            model=generation_result.model,
            tokens_in=generation_result.tokens_in,
            tokens_out=generation_result.tokens_out,
            status=generation_result.status,
            finish_reason=generation_result.finish_reason,
        )

        # Emit token attribution telemetry if flag enabled
        if args.token_attribution:
            from runtime.token_attribution import compute_token_attribution
            from homllm.generation.template_loader import TemplateLoader
            
            # Render prompt for token counting (same logic as GenerationAdapter)
            template_loader = TemplateLoader()
            rendered_prompt = template_loader.render(
                selected_template,
                template_variables,
            )
            
            # Get tokenizer from embedder
            tokenizer = getattr(embedder, '_tokenizer', None)
            
            attribution = compute_token_attribution(
                rendered_prompt=rendered_prompt,
                context_tokens=context_artifact.used_tokens,
                query=args.query,
                template_name=selected_template,
                tokens_in=generation_result.tokens_in,
                tokenizer=tokenizer,
            )
            print_telemetry("TOKEN_ATTRIBUTION", **attribution.to_dict())

        # Render user-facing output (preserves raw_text in artifacts)
        rendered_output = presentation_renderer.render(
            raw_text=generation_result.raw_text,
            status=generation_result.status,
        )
        
        # Print result - use print() directly for clean terminal output (no timestamps)
        # Always print so experiment runner can capture answer text
        print_answer_box(rendered_output)
        
        # Show status message if PARTIAL
        status_message = presentation_renderer.render_status_message(generation_result.status)
        if status_message:
            print(status_message)
        
        # Emit reasoning diagnostics if flag enabled (post-generation)
        if getattr(args, 'reasoning_diagnostics', False):
            from homllm.intelligence.reasoning_diagnostic import create_reasoning_collector
            from homllm.intelligence.assertion_readability import ReadabilityResult
            
            # Get readability result from plan, or create empty
            readability_result = (
                modification_plan.readability_result 
                if 'modification_plan' in dir() and modification_plan.readability_result 
                else ReadabilityResult.empty()
            )
            
            reasoning_collector = create_reasoning_collector(enabled=True)
            reasoning_result = reasoning_collector.collect(
                query_text=args.query,
                answer_text=generation_result.raw_text,
                readability_result=readability_result,
                context=context_artifact,
            )
            
            print_telemetry(
                "REASONING_DIAGNOSTICS",
                aggregation_missing=reasoning_result.failures.aggregation_missing,
                interaction_missing=reasoning_result.failures.interaction_missing,
                premature_surrender=reasoning_result.failures.premature_surrender,
                confidence=reasoning_result.confidence.value,
                query_types=[f.value for f in reasoning_result.query_type_flags],
                readable_blocks=reasoning_result.evidence.readable_blocks,
            )

        # Export JSON if requested
        if args.json:
            artifacts_path = Path("artifacts") / "runs" / telemetry.run_id
            telemetry.write_json(artifacts_path / "telemetry.json")

    except Exception as e:
        logger.error(f"Error during query execution: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
